apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.28.1
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      http_config:
        follow_redirects: true
        enable_http2: true

    route:
      receiver: discord
      group_by: ["namespace", "alertname"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - receiver: discord
          matchers:
            - alertname = "Watchdog"

    receivers:
      - name: discord
        webhook_configs:
          - url: https://discord.com/api/webhooks/1374109282869710999/PCYyj3vgQpW7YxSxAzhTyvfKpzpz-Rg9KVeVKGTTtTCfuZ-1fZifM4KDM4q0swPSswTg
            send_resolved: true
            http_config:
              follow_redirects: true
              enable_http2: true
            template: discord.default.message

    inhibit_rules:
      - source_matchers: ["severity = critical"]
        target_matchers: ["severity =~ warning|info"]
        equal: ["namespace", "alertname"]

      - source_matchers: ["severity = warning"]
        target_matchers: ["severity = info"]
        equal: ["namespace", "alertname"]

      - source_matchers: ["alertname = InfoInhibitor"]
        target_matchers: ["severity = info"]
        equal: ["namespace"]

      - target_matchers: ["alertname = InfoInhibitor"]

    templates:
      - "/etc/alertmanager/config/discord.tmpl"
type: Opaque