apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-secret
  namespace: monitoring
type: Opaque
stringData:
  DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1374109282869710999/PCYyj3vgQpW7YxSxAzhTyvfKpzpz-Rg9KVeVKGTTtTCfuZ-1fZifM4KDM4q0swPSswTg"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-alerts
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-alerts
  template:
    metadata:
      labels:
        app: discord-alerts
    spec:
      containers:
        - name: discord-alerts
          image: benjojo/alertmanager-discord
          ports:
            - containerPort: 9094
          envFrom:
          - secretRef:
              name: discord-webhook-secret

---
apiVersion: v1
kind: Service
metadata:
  name: discord-alerts
  namespace: monitoring
spec:
  selector:
    app: discord-alerts
  ports:
    - name: http
      port: 9094
      targetPort: 9094
