apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: prometheus-k8s
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.28.1
stringData:
  alertmanager.yaml: |-
    route:
      group_by: ['alertname', 'job']

      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h

      receiver: discord

    receivers:
    - name: discord
      discord_configs:
      - webhook_url: https://discord.com/api/webhooks/1374109282869710999/PCYyj3vgQpW7YxSxAzhTyvfKpzpz-Rg9KVeVKGTTtTCfuZ-1fZifM4KDM4q0swPSswTg
        message: |
          🔔 **Alerta Prometheus**
          *{{ .CommonAnnotations.summary }}*
          
          🔹 **Status**: {{ .Status }}
          🔹 **Alerta**: {{ .CommonLabels.alertname }}
          🔹 **Severidade**: {{ .CommonLabels.severity }}
          🔹 **Namespace**: {{ .CommonLabels.namespace }}
          🔹 **Descrição**: {{ .CommonAnnotations.description }}
          🔹 **Fonte**: {{ .ExternalURL }}
type: Opaque